spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://116.62.239.206:3306/edms
    driver-class-name: com.mysql.cj.jdbc.Driver
---
server:
  port: 8082
spring:
  profiles: beta
---
server:
  port: 8083
spring:
  profiles: prod
---
server:
  port: 80
spring:
  profiles: dev