spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url:
---
server:
  port: 8082
spring:
  profiles: beta
---
server:
  port: 8083
spring:
  profiles: prod
---
server:
  port: 80
spring:
  profiles: dev